### ISSUE TITLE
[bug]: double free

### ISSUE THREAD

**Issue by jkuri** [bleenco/bproxy#21]
After some hours of running I got 
```
double free or corruption (!prev)
```
with program crashing after that. @martinopresnik any idea?

**Comment by martinopresnik** [comment]
Could you please run bproxy with valgrind?
`valgrind --tool=memcheck --leak-check=yes ./bproxy -c ../../bproxy.json &> valgrindOutput.txt`

**Comment by jkuri** [comment]
I think I already resolved this with previous commit. It is running now for
over a week without problems.

**Comment by jkuri** [comment]
https://github.com/bleenco/bproxy/commit/6c6d3d19c3f837ae9445c7da8140390e9d5c79fa
