### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by martinopresnik** [bleenco/bproxy#51]
![transfetplot](https://user-images.githubusercontent.com/5122812/42766041-aff9f9de-8919-11e8-9b70-7147eb3b7af1.png)
![requestsplot](https://user-images.githubusercontent.com/5122812/42766044-b0276716-8919-11e8-8424-167c252e09ff.png)
![latencyplot](https://user-images.githubusercontent.com/5122812/42766046-b05d3db4-8919-11e8-9a8b-025861dcf1e0.png)

**Comment by irmana** [comment]
I think 1st and 2nd plot are the same. I would take the second one in requests.

The third plot does not make sense. Bproxy has a higher latency or?

**Comment by martinopresnik** [comment]
It has lower latency.
